Update `fortio_main.go` reference
fortio/fortio pull request #1001
Opened 2024-11-23 21:25 UTC by emmanuel-ferdman

# PR Summary
Commit cc145c47d7829751bd0f7c9986d2ff432f57b8b2 moved the `fortio_main.go` file to `cli`. This PR adjusts sources to changes.

2024-11-24 01:05 UTC, ldemailly requested changes

2024-11-24 01:05 UTC, ldemailly commented on README.md
> +You can run the histogram code standalone as a command line in [histogram/](histogram/), a basic echo HTTP server in [echosrv/](echosrv/), or both the HTTP echo and gRPC ping server through `fortio s
Thanks for noticing. let’s use main.go though as that’s the entry point and also the important part is location of the “main main” at the root

2024-12-09 22:48 UTC, ldemailly commented on README.md
> +You can run the histogram code standalone as a command line in [histogram/](histogram/), a basic echo HTTP server in [echosrv/](echosrv/), or both the HTTP echo and gRPC ping server through `fortio s
```suggestion
You can run the histogram code standalone as a command line in [histogram/](histogram/), a basic echo HTTP server in [echosrv/](echosrv/), or both the HTTP echo and gRPC ping server through `fortio server`, the fortio command line interface lives in this top level directory [main.go](main.go)
```

2024-12-09 22:50 UTC, ldemailly approved these changes

2024-12-09 22:51 UTC, ldemailly commented on README.md
> +You can run the histogram code standalone as a command line in [histogram/](histogram/), a basic echo HTTP server in [echosrv/](echosrv/), or both the HTTP echo and gRPC ping server through `fortio s
I made that change.

2024-12-30 08:30 UTC, emmanuel-ferdman commented
@ldemailly please merge this small PR when you get the chance 🙌

2025-01-26 22:04 UTC, ldemailly commented
thanks, I need to fix the CI that started to get flaky somehow

2025-03-18 20:20 UTC, mooreatv commented
CI fix is in #1022

2025-03-18 20:20 UTC, ldemailly commented
CI fix is coming in #1022 sorry for the delay

2025-03-18 20:35 UTC, merged