#164 Fortio remote test URL shouldn't require the percentiles list
fortio/fortio pull request #179
Opened 2018-03-05 20:04 UTC by olimpias

HistogramData will be experted with empty percentile array to avoid null in json. Also test is added for this.

2018-03-05 20:11 UTC, ldemailly commented
sorry the idea of #164 isn't not to deal with nil; that part works fine; the idea is that the UI should have the same default as fortio_main

2018-03-05 20:16 UTC, olimpias commented
Ah okay.

2018-03-05 20:18 UTC, ldemailly commented
the test for success is:

fortio server &

then hit 

http://localhost:8080/fortio/?labels=Fortio&url=http%3A%2F%2Flocalhost%3A8080%2Fecho&t=3s&qps=1000&save=on&r=0.0001&load=Start

it should do "50, 75, 90, 99, 99.9" percentiles; it doesn't now

2018-03-05 20:37 UTC, olimpias commented
I have tested to see the case, but it works. You can see the result json below. Percentiles are seen on DurationHistogram data.
```json
{
  "Labels": "Fortio",
  "StartTime": "2018-03-05T23:33:42.873072921+03:00",
  "RequestedQPS": "1000",
  "RequestedDuration": "3s",
  "ActualQPS": 571.8950653941345,
  "ActualDuration": 3012790465,
  "NumThreads": 8,
  "Version": "0.7.3-pre",
  "DurationHistogram": {
    "Count": 1723,
    "Min": 0.001372129,
    "Max": 0.056114808,
    "Sum": 22.966513984000002,
    "Avg": 0.013329375498549043,
    "StdDev": 0.006322253301454129,
    "Data": [
      {
        "Start": 0.001372129,
        "End": 0.0014,
        "Percent": 0.05803830528148578,
        "Count": 1
      },
      {
        "Start": 0.0016,
        "End": 0.0018000000000000002,
        "Percent": 0.2321532211259431,
        "Count": 3
      },
      {
        "Start": 0.002,
        "End": 0.0025,
        "Percent": 0.522344747533372,
        "Count": 5
      },
      {
        "Start": 0.0025,
        "End": 0.003,
        "Percent": 0.6964596633778294,
        "Count": 3
      },
      {
        "Start": 0.003,
        "End": 0.0035,
        "Percent": 0.7544979686593152,
        "Count": 1
      },
      {
        "Start": 0.0035,
        "End": 0.004,
        "Percent": 0.8705745792222868,
        "Count": 2
      },
      {
        "Start": 0.004,
        "End": 0.0045000000000000005,
        "Percent": 1.10272780034823,
        "Count": 4
      },
      {
        "Start": 0.0045000000000000005,
        "End": 0.005,
        "Percent": 1.7991874637260592,
        "Count": 12
      },
      {
        "Start": 0.005,
        "End": 0.006,
        "Percent": 2.7858386535113175,
        "Count": 17
      },
      {
        "Start": 0.006,
        "End": 0.007,
        "Percent": 5.62971561230412,
        "Count": 49
      },
      {
        "Start": 0.007,
        "End": 0.008,
        "Percent": 14.103308183401044,
        "Count": 146
      },
      {
        "Start": 0.008,
        "End": 0.009000000000000001,
        "Percent": 23.447475333720256,
        "Count": 161
      },
      {
        "Start": 0.009000000000000001,
        "End": 0.01,
        "Percent": 32.84968078932095,
        "Count": 162
      },
      {
        "Start": 0.01,
        "End": 0.012,
        "Percent": 50.435287289611146,
        "Count": 303
      },
      {
        "Start": 0.012,
        "End": 0.014,
        "Percent": 65.00290191526408,
        "Count": 251
      },
      {
        "Start": 0.014,
        "End": 0.016,
        "Percent": 75.97214161346488,
        "Count": 189
      },
      {
        "Start": 0.016,
        "End": 0.018000000000000002,
        "Percent": 84.32965757399884,
        "Count": 144
      },
      {
        "Start": 0.018000000000000002,
        "End": 0.02,
        "Percent": 90.71387115496228,
        "Count": 110
      },
      {
        "Start": 0.02,
        "End": 0.025,
        "Percent": 94.6604759141033,
        "Count": 68
      },
      {
        "Start": 0.025,
        "End": 0.030000000000000002,
        "Percent": 96.57573998839234,
        "Count": 33
      },
      {
        "Start": 0.030000000000000002,
        "End": 0.035,
        "Percent": 98.3749274521184,
        "Count": 31
      },
      {
        "Start": 0.035,
        "End": 0.04,
        "Percent": 99.41961694718515,
        "Count": 18
      },
      {
        "Start": 0.04,
        "End": 0.045000000000000005,
        "Percent": 99.53569355774812,
        "Count": 2
      },
      {
        "Start": 0.045000000000000005,
        "End": 0.05,
        "Percent": 99.94196169471851,
        "Count": 7
      },
      {
        "Start": 0.05,
        "End": 0.056114808,
        "Percent": 100,
        "Count": 1
      }
    ],
    "Percentiles": [
      {
        "Percentile": 50,
        "Value": 0.01195049504950495
      },
      {
        "Percentile": 75,
        "Value": 0.01582275132275132
      },
      {
        "Percentile": 90,
        "Value": 0.019776363636363637
      },
      {
        "Percentile": 99,
        "Value": 0.03799166666666665
      },
      {
        "Percentile": 99.9,
        "Value": 0.04948357142857149
      }
    ]
  },
  "Exactly": 0,
  "RetCodes": {
    "200": 1723
  },
  "Sizes": {
    "Count": 1723,
    "Min": 1998,
    "Max": 2002,
    "Sum": 3448072,
    "Avg": 2001.2025536854323,
    "StdDev": 0.8234479988395258,
    "Data": [
      {
        "Start": 1998,
        "End": 2000,
        "Percent": 13.116656993615786,
        "Count": 226
      },
      {
        "Start": 2000,
        "End": 2002,
        "Percent": 100,
        "Count": 1497
      }
    ],
    "Percentiles": null
  },
  "HeaderSizes": {
    "Count": 1723,
    "Min": 124,
    "Max": 124,
    "Sum": 213652,
    "Avg": 124,
    "StdDev": 0,
    "Data": [
      {
        "Start": 124,
        "End": 124,
        "Percent": 100,
        "Count": 1723
      }
    ],
    "Percentiles": null
  },
  "URL": "http://localhost:8186/fortio/?labels=Fortio\u0026url=http%253A%252F%252Flocalhost%253A8080%252Fecho\u0026t=3s\u0026qps=1000\u0026save=on\u0026r=0.0001\u0026load=Start",
  "SocketCount": 9
}
```

Are you asking for Sizes and HeaderSizes datas?

2018-03-05 21:18 UTC, ldemailly commented
no, this:

    "Percentiles": null

2018-03-06 17:04 UTC, olimpias commented
/retest

2018-03-06 19:18 UTC, ldemailly commented
to test:

- use the UI, change the values; say use "63, 81" and check you get p63 and p81 results
- use the url above, check you get the 5 defaults
- use the command line tool; check you get the 5 defaults
- use the command line tool; pass -p check it works (e.g `fortio load -p "63,81" www.google.com`)

I doubt that the pr works given what/where you made a change ?

2018-03-07 01:54 UTC, ldemailly requested changes
see comment

2018-03-07 19:17 UTC, olimpias commented
I have tested  4 case that you have mentioned, the test cases works. I think, #164 is already solved. The changes that I have done,  are unnecessary. I thought that when you say "Percentiles": null, you were talking about HeaderSizes's percentile and Size's percentile.

2018-03-07 19:42 UTC, ldemailly commented
the code in this pr is unrelated to what needs to be solved

one more time; with the url in https://github.com/istio/fortio/pull/179#issuecomment-370550762

what is missing is:
```
# target 50% 0.000371099
# target 75% 0.000461104
# target 90% 0.000540346
# target 99% 0.0007125
# target 99.9% 0.0012293
```
or in json:
```
   "Percentiles": [
      {
        "Percentile": 50,
        "Value": 0.0003710989010989011
      },
      {
        "Percentile": 75,
        "Value": 0.00046110414052697617
      },
      {
        "Percentile": 90,
        "Value": 0.0005403458213256485
      },
      {
        "Percentile": 99,
        "Value": 0.0007124999999999994
      },
      {
        "Percentile": 99.9,
        "Value": 0.0012293028000000038
      }
```

or on UI:
![screen shot 2018-03-07 at 11 39 09 am](https://user-images.githubusercontent.com/3664595/37114208-899f5204-21fc-11e8-8a34-86fdf6467bd3.png)
vs
![screen shot 2018-03-07 at 11 39 39 am](https://user-images.githubusercontent.com/3664595/37114213-8e74401e-21fc-11e8-875e-d280b4859b80.png)

2018-03-07 19:53 UTC, olimpias commented
Ah I see now, I were putting URL that you shared with me to fortio UI' URL field instead of putting it to browser url. Sorry

2018-03-10 23:13 UTC, ldemailly commented
ping :)

2018-03-12 21:47 UTC, ldemailly commented
this is good, you just need to undo your vendor change:
https://github.com/istio/istio/wiki/Vendor-FAQ#i-did-something-and-now-my-pr-has-a-vendor-change-how-do-i-fix-it-

and I need to check how come the build doesn't check that

2018-03-12 22:08 UTC, ldemailly commented
#201 fixed the issue that your pr didn't trigger a build failure when it should have, now it does

2018-03-12 22:10 UTC, ldemailly commented on ui/uihandler.go
> +	if len(percList) == 0 {
can you make the difference between p= isn't provided, in which case we use defaults and p= is empty in which case we should respect the will of the caller to not calculate any % ?

2018-03-13 07:23 UTC, ldemailly commented on Gopkg.lock
> +  name = "cloud.google.com/go"
ahem **NO** please do not change Gopkg.lock (nor vendor)

2018-03-13 07:26 UTC, ldemailly commented on ui/uihandler.go
> +	if len(percList) == 0 && !strings.Contains(r.URL.RawQuery,"p=") {
cool, that's creative and will do ! thanks!

2018-03-13 07:27 UTC, olimpias commented
I mess up about vendor.

2018-03-13 07:27 UTC, ldemailly commented
are you having difficulties with
https://github.com/istio/istio/wiki/Vendor-FAQ#i-did-something-and-now-my-pr-has-a-vendor-change-how-do-i-fix-it-

please tell me exactly what doesn't work so I can improve the instructions on how to fix vendor when you accidentally changed it

then we can merge this

2018-03-13 07:27 UTC, ldemailly approved these changes

2018-03-13 07:28 UTC, ldemailly commented
please make sure to resolve "This branch is out-of-date with the base branch" first (click the button for instance, or do it on your local copy)

2018-03-13 07:29 UTC, olimpias commented
When I use git submodule update. There are three diffs occurred. I was expecting that only vendor to be diff.

2018-03-13 07:30 UTC, ldemailly commented
ps: replace https://github.com/istio/istio.git by https://github.com/istio/fortio.git  in the instructions! the wiki is for istio but it's same setup here

2018-03-13 07:33 UTC, ldemailly commented
awesome thanks!

2018-03-13 07:33 UTC, olimpias commented
I think it is okay now :). Thanks

2018-03-13 07:34 UTC, ldemailly commented
a test would have been great too but this is ok, I'll test it later

2018-03-13 07:36 UTC, olimpias commented
I can add unit test tomorrow.

2018-03-13 07:38 UTC, ldemailly commented
hmm not sure why the linters aren't happy, some whitespace issue maybe?

2018-03-13 07:39 UTC, olimpias commented
Yes, while I was reverse committing. I made white space mistake.

2018-03-13 07:55 UTC, merged